name: hey_smile
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  #Icons
  cupertino_icons: 1.0.8
  phosphor_flutter: 2.1.0
  lottie: 3.3.1

  #State management and routing
  provider: 6.1.5+1
  go_router: 17.0.0

  #Storage
  shared_preferences: 2.5.3
  flutter_secure_storage: 9.2.4

  #Utilities
  table_calendar: 3.1.2
  dio: 5.9.0

  # For guided camera usage
  google_mlkit_face_detection: 0.13.1
  google_mlkit_pose_detection: 0.14.0
  flutter_tts: 4.2.3
  image: 4.5.4
  camera: 0.11.2+1
  image_picker: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 
  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
